---

- name: Install wget
  yum:
    name: wget
    state: latest

- name: Install unzip
  yum:
    name: unzip
    state: latest

- name: terraform install
  unarchive:
    src: https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip
    dest: /usr/bin
    remote_src: True

